spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test
    password: abc
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update